version: "3.8"

services:
  redis:
    image: 'bitnami/redis:latest'
    container_name: redis
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
      interval: 60s
      timeout: 5s
      retries: 5
      start_period: 0s
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - default

  app:
    build:
      context: ./
      dockerfile: ./docker/php/Dockerfile
    container_name: app
    volumes:
      - ./app:/source
    working_dir: /app
    healthcheck:
      test: curl --fail http://nginx/ping || exit 1
      interval: 60s
      timeout: 5s
      retries: 5
      start_period: 30s
    environment:
      KAFKA_BROKERS: "kafka:9092"
      PHP_CS_FIXER_IGNORE_ENV: 1
    depends_on:
      - redis
    networks:
      - default

  nginx:
    build:
      context: ./
      dockerfile: ./docker/nginx/Dockerfile
    container_name: nginx
    tty: true
    healthcheck:
      test: curl --fail http://localhost/ping || exit 1
      interval: 60s
      timeout: 5s
      retries: 5
      start_period: 30s
    ports:
      - "80:80"
      - "443:443"
    links:
      - app
    networks:
      - default

networks:
  default:
    name: docker_default
    external: true