parameters:
    env(MONGODB_URL): ''
    env(MONGODB_DB): ''

services:
    _defaults:
        autowire: true
        autoconfigure: true

    _instanceof:
        Acme\Shared\Domain\Bus\Query\QueryHandler:
            tags:
                - { name: messenger.message_handler, bus: query.bus }
        Acme\Shared\Domain\Bus\Command\CommandHandler:
            tags:
                - { name: messenger.message_handler, bus: query.bus }

    Acme\:
        resource: '../src/'
        exclude:
            - '../src/Kernel.php'


    controllers:
        namespace: Acme\
        resource: '../src/*/Port/Http/Controller/*'
        tags: ['controller.service_arguments']