# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    env(MONGODB_URL): ''
    env(MONGODB_DB): ''

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name

    _instanceof:
        Acme\Shared\Domain\Bus\Event\DomainEventSubscriberInterface:
            tags: ['app.domain_event_subscriber']

        Acme\Shared\Domain\Bus\Command\CommandHandlerInterface:
            tags: #- name: app.command_handler
                -
                    name: messenger.message_handler
                    bus: command
                    handles: Acme\Shared\Domain\Bus\Command\CommandInterface

        Acme\Shared\Domain\Bus\Query\QueryHandlerInterface:
            tags:
                -
                    name: messenger.message_handler
                    bus: query
                    handles: Acme\Shared\Domain\Bus\Query\QueryInterface

    Acme\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            #- '../src/*/Domain/Entity/'
            - '../src/Kernel.php'
    Acme\Shared\:
        resource: '../src/Shared/'

    Acme\Shared\Infrastructure\Bus\Event\DomainEventDispatcher:
        arguments: [!tagged_iterator app.domain_event_subscriber]
        lazy: true

    controllers:
        namespace: Acme\
        resource: '../src/*/Port/Http/Controller/*'
        tags: ['controller.service_arguments']