framework:
    cache:
        prefix_seed: arch2/app
        app: cache.adapter.redis
        system: cache.adapter.redis
        default_redis_provider: '%env(REDIS_CACHE_DSN)%'

        # Namespaced pools use the above "app" backend by default
        #pools:
            #my.dedicated.cache: null
