framework:
    messenger:
        enabled: true
        default_bus: query.bus
        buses:
            kafka.bus: ~
            command.bus: ~
            query.bus: ~
            event.bus:
                default_middleware: allow_no_handlers

        transports:
            sync: 'sync://'
            kafka.products:
                dsn: '%env(resolve:MESSENGER_TRANSPORT_DSN_KAFKA)%'
                serializer: 'Acme\Shared\Infrastructure\Bus\Kafka\KafkaJsonSerializer'
                options:
                    topic: 'products'
                    group_id: 'consumer-products-messenger'
                    receiveTimeout: 60000
            kafka.prices:
                dsn: '%env(resolve:MESSENGER_TRANSPORT_DSN_KAFKA)%'
                serializer: 'Acme\Shared\Infrastructure\Bus\Kafka\KafkaJsonSerializer'
                options:
                    topic: 'prices'
                    group_id: 'consumer-prices-messenger'
                    receiveTimeout: 60000

        routing:
            'Acme\Shared\Domain\Bus\Command\CommandInterface': sync
            'Acme\Shared\Domain\Bus\Query\QueryInterface': sync
            'Acme\Shared\Domain\Bus\Kafka\KafkaMessageInterface': [kafka.products, kafka.prices]


# when@test:
#    framework:
#        messenger:
#            transports:
#                # replace with your transport name here (e.g., my_transport: 'in-memory://')
#                # For more Messenger testing tools, see https://github.com/zenstruck/messenger-test
#                async: 'in-memory://'
